### PR TITLE
doc for norm1 & norm2

### PR DESCRIPTION
**Pull request by yizhang-yiz**
#### Submission Checklist

- [x] Builds locally 
- [x] New functions marked with `` `r since("VERSION")` ``
- [x] Declare copyright holder and open-source license: see below

#### Summary
Document `norm1` & `norm2` as array reduction ops.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Metrum Research Group.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
This fails to build for me locally. I think you need to escape the underscores in the type `row_vector` in the latex portion

**Comment by yizhang-yiz** [comment]
My bad. It can be built now. 

OT:
Every time when I use
```bash
Rscript -e "bookdown::render_book('index.Rmd', output_format='bookdown::pdf_book')"
```
to build I get the error
```bash
fatal error: file read error: "file not found" when accessing "/path_to_docs/docs/src/language.dtd"
```
and I have to remove the corresponding line in `src/stan.xml`, though I didn't investigate.

**Review by WardBrian — APPROVED** [review]
LGTM. Feel free to merge when the stanc PR is approved

**Comment by WardBrian** [comment]
> ```shell
> language.dtd
> ```

Huh, that's odd. I don't get that locally, and I don't think our CI had any issues building the docs for the most recent version. Maybe it's a pandoc version issue?

**Comment by yizhang-yiz** [comment]
Could be. I'll come back to it. Thanks.

**Comment by WardBrian** [comment]
I just checked and pandoc has updated which means Stan is officially supported (pandoc 2.17.1 or newer). In theory we can delete stan.xml file now if we update our CI machines - @serban-nicusor-toptal is this something we control?

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian the docs here we're still building on our old osx which we have full control over, at the same time on flatiron we're using docker where we can also very easily change package versions.
Is there anything else to update other than pandoc to 2.17.1+ ? I can do it in the morning

**Comment by WardBrian** [comment]
I think just updating pandoc would be good. We can decide later if we still want to override the built in highlighting with our own

**Comment by serban-nicusor-toptal** [comment]
pandoc has been updated on our docs build machine ( gelman mac ) to:
```
$ pandoc --version
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
```

**Comment by bob-carpenter** [comment]
@WardBrian and @yizhang-yiz --- are you still waiting on something to merge this?

**Comment by WardBrian** [comment]
The stanc PR hasn’t been merged yet, there was a C++ issue which still needs to be resolved

**Comment by yizhang-yiz** [comment]
There's a missing case to be impl in Math. I haven't found time to do it.

**Pull request merged**
