### PR TITLE
Documentation generated from Jenkins for docs-2-22

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submission Checklist

- [ ] Builds locally 
- [ ] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mcol** [comment]
Is also adding links from the 2.21 version to the 2.22 (something like b88ae470431288562c5c59444790982d4)? I can't find them explicitly, but maybe something is already in place?

**Comment by mitzimorris** [comment]
good catch - the Jenkinsfile should also run python script 'link_to_latest.py' - it's the thing that goes in and does a brute-force edit of the html so that all the pages link to the unversioned URL (which then redirects to current version). 

this solution is a https://en.wikipedia.org/wiki/Rube_Goldberg_machine, powered by Jenkins, thanks to @serban-nicusor-toptal!

**Comment by serban-nicusor-toptal** [comment]
PR [here](https://github.com/stan-dev/docs/pull/140)

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal  - is this PR necessary or will script take care of it?
this one doesn't have redirects, and 2_21 docs don't have link to latest.
happy to generate the 2_22 docs from current master for you.

**Pull request merged**
