### PR TITLE
Document new reserved keywords

### LINKED ISSUE #145: Update list of reserved keywords
#### Summary:
Given the switch to stanc3, there are a few more keywords that should be listed as reserved (see https://discourse.mc-stan.org/t/list-of-stanc3-new-reserved-keywords/12948/5). The relevant file is `src/reference-manual/expressions.Rmd`.

#### Additional Information:
Should ideally be done before publishing docs for 2.22.

### PR DESCRIPTION
**Pull request by mcol**
#### Submission Checklist

- [X] Builds locally 
- [X] Declare copyright holder and open-source license: see below

#### Summary
Fixes #145.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Marco Colombo

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mcol** [comment]
@mitzimorris could you check this and regenerate the 2.22 docs if it's fine?

**Comment by mcol** [comment]
Thanks! Can you or @serban-nicusor-toptal regenerate the docs for 2.22? I have more docs to add for functions introduced in 2.23 that I don't want to get tangled up with 2.22 docs.

**Comment by mitzimorris** [comment]
done!

**Comment by mcol** [comment]
Awesome, thanks!

**Pull request merged**
