### PR TITLE
call make_stan_functions()

### PR DESCRIPTION
**Pull request by bgoodri**
#### Submission Checklist

- [X] Builds locally (but needs to fix merge conflicts)
- [X] Declare copyright holder and open-source license: see below

#### Summary

This PR defines and calls a `make_stan_functions` Python function to (re)create the stan-functions.txt file that is used by 

https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/tools/stan-functions.txt

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Trustees of Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
@bgoodri  - thanks for sharing your code.
this should be implemented as a stand-alone python program, not as part of build.py.  I would be willing to do this for you.

**Comment by bgoodri** [comment]
Either way is fine with me.

**Comment by kaz-yos** [comment]
The Emacs `stan-mode` (https://github.com/stan-dev/stan-mode) heavily relies on the `stan-functions.txt` file. So if it can keep up with the latest Stan automatically, that will be great!

**Comment by mitzimorris** [comment]
closing this - will be implemented as part of https://github.com/stan-dev/docs/pull/180

**Pull request closed without merging**
