### PR TITLE
Expand documentation around `xc` in integration

### PR DESCRIPTION
**Pull request by vdeni**
#### Submission Checklist

- [X] Builds locally **NOTE** I *do* get this warning with `bookdown::render_book('index.Rmd')`
```
`Warning message:
In file.rename(files[i], files2[i]) :
  cannot rename file 'optimization.html' to '_book/optimization.html', reason 'No such file or directory'`
```
- [X] New functions marked with `` `r since("VERSION")` ``
- [X] Declare copyright holder and open-source license: see below

#### Summary

Added another example to the one-dimensional integration chapter. Tried to use it to clarify the usage of `xc`.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): I am the copyright holder.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Hvala @vdeni!

Thanks for the contribution and sorry it took us so long to get to it. I am not really familiar with the 1d integration implementation, maybe @yizhang-yiz can review?

**Review by yizhang-yiz — COMMENTED** [review]
Thanks for contributing. 

Do I understand correctly that "numerator" is used here for "integrand"? Is this an established usage of the term?

Otherwise everything looks good.

**Comment by vdeni** [comment]
Hi, thanks for getting back to me!

I've used `numerator` as the variable name as what we're doing is integrating the numerator of the expression for the expectation of the truncated distribution [wikipedia](https://en.wikipedia.org/wiki/Truncated_distribution):

image

In hindsight, maybe not the best choice of words, yes.

**Review by yizhang-yiz — APPROVED** [review]

**Comment by spinkney** [comment]
is this good to go? I've been very confused in the past about how to use `xc` in the past and am looking forward to having this in

**Comment by bob-carpenter** [comment]
As soon as something's approved and has passed tests, you can merge.  So I'll just merge this.

**Pull request merged**
