### PR TITLE
add generalized inverse

### PR DESCRIPTION
**Pull request by spinkney**
I <strike>haven't</strike> built it locally and I put a lot more documentation then is typical since there was some confusion about when the generalized inverse is differentiable. Having cleared it up with @bbbales2 I figured users would also have similar questions so I put an example in the docs. 

#### Submission Checklist

- [x] Builds locally 
- [x] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sean Pinkney

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by spinkney** [comment]
Screen Shot 2020-12-19 at 8 59 13 AM

**Comment by bbbales2** [comment]
@spinkney I made some edits, have a look. I think we should add a citation to the Goloub thing since Googling "locally constant rank" doesn't give me a Wikipedia page.

I added at the end the line "Because HMC depends on the derivatives existing, this lack of differentiability creates undefined behavior." which seems correct, but I don't like it now because you could say the same for basically any function that suffers this (which would be a lot).

**Comment by bbbales2** [comment]
Looking for how to add citations, hopefully there's something we can copy-paste

**Comment by spinkney** [comment]
put in the reference in https://github.com/stan-dev/docs/blob/master/src/bibtex/all.bib

```
@article{golub:1973,
 ISSN = {00361429},
 URL = {http://www.jstor.org/stable/2156365},
 abstract = {For given data (ti, yi), i = 1, ⋯, m, we consider the least squares fit of nonlinear models of the form $\eta(\mathbf{a, \alpha};t) = \sum^n_{j = 1} a_j \varphi_j(\mathbf{\alpha};t),\quad \mathbf{a} \in \mathscr{R}^n, \mathbf{\alpha} \in \mathscr{R}^k.$ For this purpose we study the minimization of the nonlinear functional r(a, α) = ∑m i = 1 (yi - η(a, α, ti))2. It is shown that by defining the matrix {Φ(α)}i,j = φj(α; ti), and the modified functional r2(α) = |y - Φ(α)Φ+ (α)y|2 2, it is possible to optimize first with respect to the parameters α, and then to obtain, a posteriori, the optimal parameters $\hat{\mathbf{a}}$. The matrix Φ+(α) is the Moore-Penrose generalized inverse of Φ(α). We develop formulas for the Frechet derivative of orthogonal projectors associated with Φ(α) and also for Φ+(α), under the hypothesis that Φ(α) is of constant (though not necessarily full) rank. Detailed algorithms are presented which make extensive use of well-known reliable linear least squares techniques, and numerical results and comparisons are given. These results are generalizations of those of H. D. Scolnik [20] and Guttman, Pereyra and Scolnik [9].},
 author = {G. H. Golub and V. Pereyra},
 journal = {SIAM Journal on Numerical Analysis},
 number = {2},
 pages = {413--432},
 publisher = {Society for Industrial and Applied Mathematics},
 title = {The Differentiation of Pseudo-Inverses and Nonlinear Least Squares Problems Whose Variables Separate},
 volume = {10},
 year = {1973}
}
```

and then \cite{golub:1973}

I gotta run right now, can do it later

**Comment by bbbales2** [comment]
Citation added, thanks!

**Comment by rok-cesnovar** [comment]
The signature was added to the language just now so feel free to merge this whenever its ready.

**Comment by bbbales2** [comment]
@spinkney lemme know what you think about the changes

**Comment by spinkney** [comment]
@bbbales2 looks good!

**Pull request merged**
