### PR TITLE
Update multivariate priors for hierarchical models beta variance description

### PR DESCRIPTION
**Pull request by spinkney**
The description of the variance was confusing as to why we didn't multiply by LL^T (at least to me). I made it clearer (at least to me).

Submission Checklist
 - [x] Builds locally
 - [x] Declare copyright holder and open-source license: see below

Copyright and Licensing
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sean Pinkney

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:

Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by syclik — COMMENTED** [review]
For what it's worth, I find the wording to be an improvement. I trust it builds properly?

**Comment by spinkney** [comment]
@syclik, I just pushed an update since the var(beta) isn't quite E(beta * beta^T). I was thinking in terms of the Cholesky factors. I spelled it out more clearly. It's a bit more verbose, but I actually think it connects a lot of dots for new users. It does compile. Here's the snippet of changes,

image

**Comment by rok-cesnovar** [comment]
@syclik mind approving if you are good with the changes? Thanks!

**Review by syclik — APPROVED** [review]
Thank you!

**Comment by syclik** [comment]
@spinkney, feel free to merge!

**Pull request merged**
