### PR TITLE
Build with syntax highlighting from pandoc

### LINKED ISSUE #463: syntax highlighting for code fragments
#### Summary:

Use the highlights.js library  for Stan code in the Stan User's Guide.

#### Description:

Stan highlighting has been updated recently - lets add this to the Stan User's Guide.
For the HTML, this requires more config and proper stylesheets.

Investigate which manuals need this - if they don't contain extended code fragments, the
impelmentation and maintenance burden aren't worth it.

Investigate ways to get styling into pdfs - can this be done w/out having to add
more latex tags into all the Rmd files?

#### Additional Information:
announcement here:  https://discourse.mc-stan.org/t/stan-the-gathering-jan-13-11am-est/24944/9

#### Current Version:
v2.29.0

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Builds locally 
- [x] New functions marked with `` `r since("VERSION")` ``
- [x] Declare copyright holder and open-source license: see below

#### Summary

Closes #463. Use pandoc's [--syntax-definition](https://pandoc.org/MANUAL.html#option--syntax-definition) flag to pass the upstream stan.yml (from [skylighting](https://github.com/jgm/skylighting/blob/master/skylighting-core/xml/stan.xml)).

This highlighting will be built in to future versions of pandoc and we can remove the config in `_output.yml`

Previews:
pdf highlighting
html highlighting

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by mitzimorris — COMMENTED** [review]
this looks great.
one comment regarding `stan.xml` - how do we make sure it keeps up with the Stan language.  in particular, it doesn't handle the new array syntax.

**Comment by WardBrian** [comment]
We can update the `stan.xml` in our repo whenever we need to. To keep the one used by Pandoc itself up to date, there would need to be a merge request made to the Kate syntax definitions hosted here: https://invent.kde.org/frameworks/syntax-highlighting

**Comment by WardBrian** [comment]
`array`, `complex`, and other new keywords like `profile` added to our local `stan.xml`. 

I'm going to see about upstream inclusion but I'm having a hard time building and running their test framework

**Review by mitzimorris — APPROVED** [review]
awesome!

**Pull request merged**
