### PR TITLE
Clarify the double exponential distribution docs

### PR DESCRIPTION
**Pull request by hhau**
#### Submission Checklist

- [x] Builds locally 
- [x] Declare copyright holder and open-source license: see below

#### Summary

From [shira on discourse](https://discourse.mc-stan.org/t/error-in-stan-documentation-about-double-exponential/15962/).

This PR aligns the parameterisation of the exponential distribution, normal distribution and double-exponential distribution with both the double exponential doc, and the rest of the Stan doc.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Andrew Manderson 

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by shiraamitchell** [comment]
looks great to me !

**Comment by shiraamitchell** [comment]
Thanks, @mitzimorris ! I don't yet see the change [here](https://mc-stan.org/docs/2_23/functions-reference/double-exponential-laplace-distribution.html), did we correct the wrong code ?

**Comment by mitzimorris** [comment]
it will be correct in the 2.24 release docs

**Comment by shiraamitchell** [comment]
makes sense, thank you !!

**Pull request merged**
