### PR TITLE
Corrected range of arctan

### PR DESCRIPTION
**Pull request by kwichmann**
Range of atan is not -pi to pi, but -pi/2 to pi/2.

#### Submission Checklist

- [ ] Builds locally 
- [ ] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Thank you!

**Comment by spinkney** [comment]
hey Rok this messes up the file name. The file is now name `atan_range` when it should be `real-valued_basaic_functions.Rmd`

**Comment by rok-cesnovar** [comment]
Ah yes, I see. I missed the filename change. Will post a fix immediately.

**Comment by rok-cesnovar** [comment]
Ah nevermind, you already did! Thanks! :)

**Pull request merged**
