### PR TITLE
add beta_neg_binomail docs

### PR DESCRIPTION
**Pull request by lingium**
#### Submission Checklist

- [x] Builds locally
- [x] New functions marked with `` <<{ since VERSION }>>``
- [x] Declare copyright holder and open-source license: see below

#### Summary
Add documentation for function beta_neg_binomial_lccdf. See https://github.com/stan-dev/math/pull/3114.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Zhi Ling

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
Hi @lingium - since it looks like they’re all going to make it into this release, do you want to go ahead and add the lcdf, cdf, and RNG signatures in this PR?

**Comment by lingium** [comment]
Hi @WardBrian , yes, let me add them all here. BTW when will be the next release?

**Comment by WardBrian** [comment]
The release candidates will go out next week, and unless any issues get discovered the release will be 12/9

**Review by WardBrian — APPROVED** [review]
Thanks!

**Pull request merged**
