### PR TITLE
Remove lp__ from list deprecated features in the reference manual

### PR DESCRIPTION
**Pull request by mcol**
#### Submission Checklist

- [X] Builds locally 
- [X] Declare copyright holder and open-source license: see below

#### Summary
Addresses #10.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Marco Colombo

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mcol** [comment]
So are you suggesting to put that text under an "Eliminated Features" section rather than removing it?

**Comment by bob-carpenter** [comment]
Yes, please.  'd like to see the deprecation chapter broken into deprecated and eliminated sections, or I'd like to see a new chapter for eliminated functions.  I don't have a preference.

The goal is to have bread crumbs for people to translate older Stan models into the current version.

Thanks!

**Comment by mcol** [comment]
I put the old text in a separate chapter, adding a little bit at the beginning as introduction.

**Comment by bob-carpenter** [comment]
Thanks much for updating!  Looks great.

**Pull request merged**
