### PR TITLE
vectorized complex accessors

### PR DESCRIPTION
**Pull request by bob-carpenter**
#### Description

Adds vectorized signature doc for complex accessors.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Can someone please review and merge this?  Thanks.

**Comment by WardBrian** [comment]
This as written leads to duplication with the later section on matrices, as I pointed out here: https://github.com/stan-dev/docs/issues/684#issuecomment-1789419652

**Comment by WardBrian** [comment]
I think a link seems reasonable? I believe having the information in both sections makes sense, but the existing page has a bunch of exposition that is good to not duplicate. 

We definitely have some mixed conventions here, but I think the original discoverability issue would be solved by a link on the scalar version's page

**Comment by bob-carpenter** [comment]
This is the tip of a much larger iceberg of problems that need to be solved in more generality, so I'm closing this little PR.

**Pull request closed without merging**
