### PR TITLE
Add documentation for Poisson-binomial distribution

### PR DESCRIPTION
**Pull request by dirmeier**
#### Submission Checklist

- [x] Builds locally 
- [x] Declare copyright holder and open-source license: see below

#### Summary

Adds documentation for Poisson-binomial distribution related functions

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Simon Dirmeier

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by dirmeier** [comment]
Ciao all,

@rok-cesnovar, as discussed in https://github.com/stan-dev/docs/issues/298, this PR adds docu for the Poisson-binomial distribution. 

I am not sure about one part though: in `math` the lpmf can take as arguments `std::vector<int>` and  `std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1>>` (like [here](https://github.com/stan-dev/math/blob/develop/test/unit/math/prim/prob/poisson_binomial_test.cpp#L41)).  To which types is that translated to in Stan, so I can add it to the docu?

Best, 
Simon

**Comment by rok-cesnovar** [comment]
Hey,

Thanks!

std::vector<int> is int[]
Eigen::Matrix<double, Eigen::Dynamic, 1>;
 is a vector
Eigen::Matrix<double, 1, Eigen::Dynamic> is a row_vector and when both are dynamic its a matrix.

**Comment by dirmeier** [comment]
Thanks, but what is `std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1>>` ?

**Comment by rok-cesnovar** [comment]
Ah sorry, misread. That is an array of vectors, so vector [].

**Comment by jgabry** [comment]
Thanks Simon!

**Comment by dirmeier** [comment]
Ciao @rok-cesnovar and @jgabry , all done. 
Best,
Simon

**Comment by bbbales2** [comment]
@dirmeier I updated the docs here a bit.

I removed the `vector[m] x[n]` signatures. The distributions docs use `vectors` to indicate an argument can either be a `vector` or an `array[] vector`. It's a bit weird -- see the multivariate normal docs [here](https://mc-stan.org/docs/2_26/functions-reference/multivariate-normal-distribution.html)

If that looks alright I'll merge.

**Comment by dirmeier** [comment]
Ciao @bbbales2 , sorry, this went by unnoticed. Looks good to me, thanks!

**Pull request merged**
