### PR TITLE
Add support for a dark theme

### LINKED ISSUE #738: add dark mode for website
#### Summary:

User request:  allow dark mode theming - https://discourse.mc-stan.org/t/new-improved-stan-docs-website/34349/5

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Builds locally
- [x] New functions marked with `` <<{ since VERSION }>>``
- [x] Declare copyright holder and open-source license: see below

#### Summary

Closes #738.

This adds a basic dark theme and cleans up some of our existing theme customizations

image

It still needs some color tweaks, especially for code blocks. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
I'm very happy if you or anyone else wants to tweak the colors here, I was mainly trying to get _something_ working in Dark mode.

**Comment by mitzimorris** [comment]
yes, happy to tweak colors.

**Comment by WardBrian** [comment]
Tweaked colors:
image

**Comment by mitzimorris** [comment]
text color looks good!   not as harsh as before.

**Comment by WardBrian** [comment]
I'm sure we could continue tweaking forever, but I think it is over the "good enough" line now. Especially because the code blocks are actually readable!

**Review by mitzimorris — APPROVED** [review]
many thanks for cleaning this up!

**Pull request merged**
