### PR TITLE
Change url scheme during builds

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Builds locally 
- [ ] New functions marked with `` `r since("VERSION")` ``
- [x] Declare copyright holder and open-source license: see below

#### Summary

This changes to the URL scheme discussed in #532. The latest version is now copied into the unversioned path, rather than redirects

We will really want to do #451 as a follow on, and when the update is out we should update the links https://mc-stan.org/users/documentation/ to point to the version without `2_xx`

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by serban-nicusor-toptal — APPROVED** [review]
LGTM!

**Comment by WardBrian** [comment]
@serban-nicusor-toptal would there be a way to run this ahead of time just to see what the PR it generates looks like? We can feed it a dummy version like 9.99 or something, make sure everything looks like we expect, then close the generated PR and merge this

**Comment by serban-nicusor-toptal** [comment]
Yes, you can replay [Build #5](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FBuildDocs/detail/BuildDocs/5/pipeline) ( points to /url-change )
It errors out in build.py atm, need to figure out why

**Comment by serban-nicusor-toptal** [comment]
Seems to error out here:
```
cd /private/tmp/docs/src/functions-reference && \
Rscript -e "bookdown::render_book('index.Rmd', output_format='bookdown::pdf_book')"
```

```
/usr/local/bin/pandoc +RTS -K512m -RTS _main.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.tex --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /Library/Frameworks/R.framework/V
ersions/3.5/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /var/folders/yt/r3s4vflx5ysc089qpgvgt6t00000gw/T//RtmpRoOrct/fileae5c181c3bc4 --self-contained --table-of-contents
 --toc-depth 2 --number-sections --highlight-style tango --pdf-engine pdflatex --include-in-header header.tex --include-after-body postamble.tex --variable graphics --wrap preserve --syntax-definition ../stan.xml --variable tables=yes --standalone -Mhas-frontmatter=false --citeproc
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/pandoc
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/pandoc
  Expected in: /usr/lib/libSystem.B.dylib

Error: pandoc document conversion failed with error 5
Execution halted
```

**Comment by WardBrian** [comment]
That looks odd to me, does that happen if you run without this PR? Maybe because we updated pandoc?

**Comment by serban-nicusor-toptal** [comment]
I ran it on master, same thing.
pandoc does throw a document conversion error

**Comment by WardBrian** [comment]
Could we re-install pandoc on that machine?

**Comment by serban-nicusor-toptal** [comment]
Yes, on it.

**Comment by WardBrian** [comment]
On my machine I have 
```
pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1
```

**Comment by serban-nicusor-toptal** [comment]
Machine: ```pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
```

**Comment by serban-nicusor-toptal** [comment]
I've downgraded to `2.14.0.3`
It's weird because on master it builds just fine but errors out on this branch ...
```
/private/tmp/docs
/private/tmp/docs/src/functions-reference
render functions-reference as pdf
Command Rscript -e "bookdown::render_book('index.Rmd', output_format='bookdown::pdf_book')" failed
Traceback (most recent call last):
  File "/private/tmp/docs/build.py", line 130, in <module>
    main()
  File "/private/tmp/docs/build.py", line 126, in main
    make_docs(docspath, stan_version, doc, formats)
  File "/private/tmp/docs/build.py", line 57, in make_docs
    shexec(command)
  File "/private/tmp/docs/build.py", line 35, in shexec
    raise Exception(returncode)
Exception: 1
```

**Comment by WardBrian** [comment]
Probably this branch needs to be updated to have #533 merged in if I had to guess

**Comment by WardBrian** [comment]
The generated PR still links to the old mc-stan.org Jenkins which we should also fix

**Comment by WardBrian** [comment]
@serban-nicusor-toptal I am going to be away until Tuesday, so we can hold off on more trial runs until then I think

**Comment by serban-nicusor-toptal** [comment]
Sure, I've already changed the url and ran [this one](https://github.com/stan-dev/docs/pull/543), if it still needs any change we can do it later.

**Comment by WardBrian** [comment]
The branch created by #543 looked great to me, so I think we can do this. We will definitely want a better 404 before the next release

**Pull request merged**
