### PR TITLE
Update unit-vector transform

### PR DESCRIPTION
**Pull request by spinkney**
Submission Checklist
 - [x] Builds locally
 - [x] Declare copyright holder and open-source license: see below

Summary
update unit-transform to indicate that no jacobian adjustment is performed

@bbbales2 please review

Copyright and Licensing
Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sean Pinkney

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:

Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bbbales2** [comment]
Apologies for taking so long to get to this. I just keep getting confused.

I think now what is:

Stan samples in an unconstrained space (x1, x2, x3, ...). We transform this to a coordinate system (r, q1, q2, q3, ...) where `r = sqrt(sum(x^2))`.

We handwave the problem with the map at 0 away by putting a zero avoiding prior on `r` and saying we'll stay away.

Now the user can specify a distribution on `p(q1, q2, q3, ...)`. Because we put a proper prior on `p(r)`, our prior on `p(r, q1, q2, q3, ...)` is always proper. Because we never print `r`, we're effectively just integrating over that variable in all the outputs.

I wonder if there's a way to say this where we don't even have to mention a change of coordinates though? Like certainly `p(x1, x2, x3, ...) \propto e^(-0.5 sum(x^2))` is a valid distribution.

@yao-yl do you know?

**Comment by yao-yl** [comment]
@bbbales2 what do you mean? p(x1, x2, x3, ...) = e^(-0.5 sum(x^2))  is certainly not p(r)= e^(-0.5 r^2) without Jacobian. Also how is your discussion related to this PR since unit vector fixes r=1?

**Comment by bbbales2** [comment]
> without Jacobian

Well the 1-to-1 map thing doesn't exist anyway, so there isn't a Jacobian to speak of, and `p(x1, x2, x3, ...)` as defined there is definitely a normalizable distribution.

> since unit vector fixes r=1?

`r` isn't fixed in the underlying parameter space.

**Comment by spinkney** [comment]
> > since unit vector fixes r=1?
> 
> `r` isn't fixed in the underlying parameter space.

I don't know what you mean by the underlying parameter space. `r` could be anything, you're right. In 3d this generates points on the unit sphere, if r x / ||x|| then we set r = 1 since it's just the magnitude. So we take an arbitrary value for r (though 1 does make for a good choice).

**Comment by rok-cesnovar** [comment]
The online docs will be rebuilt after the 2.27 release next week so just bumping this if there is a chance we add it.

**Comment by bbbales2** [comment]
Woof, I have gone back to this a few times and keep getting confused. I can try again on the weekend when I'm doing adjoint docs.

**Comment by bbbales2** [comment]
I remain stumped.

So from our docs: https://mc-stan.org/docs/2_26/reference-manual/unit-vector-section.html#ref-Marsaglia:1972

This says both:

"To generate a unit vector, Stan generates points at random in R^n with independent unit normal distributions, which are then standardized by dividing by their Euclidean length."

And then also later:

"In this case, the determinant of the Jacobian is proportional to e^{−y^T * y)"

The first problem is we don't generate random points when we're sampling, so that first bit is wrong. Secondly, I don't think there is any Jacobian since we don't have a 1 to 1 map or anything.

What we effectively do is:

```
parameters {
  vector[N] x;
}

transformed parameters {
  vector[N] y = x / sqrt(dot_self(x));
}

model {
  x ~ normal(0, 1);
}
``` 

I'd like to just describe the code like that in the documents, but I'm stumped on what it means to put a prior on y there.

**Comment by yao-yl** [comment]
@bbbales2 :  
> I don't think there is any Jacobian since we don't have a 1 to 1 map or anything.

1-1 or not, we do need some adjustment (even without calling it Jacobian), if we want a prior on the unit vector `y~foo()`?

**Comment by bob-carpenter** [comment]
@bgoodri is the expert here.  This is Marsaglia's method.  The key is that if you take

```
y[1], ..., y[N] ~ normal(0, 1)
```

then let

```
z = y / sqrt(y' * y)
```

then you have `z' * z = 1` and

```
z ~ uniform-hypersphere(N)
```

The normal log density is the adjustment for the transformation even though it's not one-to-one.  So when you write this in Stan:

```
parameters {
  unit_vector[N] z;
}
```

it's equivalent to this:

```
parameters {
  vector[N] y;
}
transformed parameters {
  unit_vector[N] z = y / sqrt(y' * y);
}
model {
  y ~ std_normal();
}
```

The log density adjustment from the standard normal would be dropped for optimization.

**Comment by spinkney** [comment]
@bob-carpenter you wrote in https://github.com/stan-dev/math/issues/2590

> @spinkney If you could open a docs issue with a suggestion on which docs to fix (reference manual or user's guide or both) and what you'd like to see, I can write it.

This was my attempt at fixing the docs for this.

**Comment by bob-carpenter** [comment]
@spinkney --- did you want to update, or should I include an update for this when I add the affine transform section?  I'm trying to close all the longstanding docs PRs.

**Comment by spinkney** [comment]
I'm convinced we should be doing the spherical transform instead of this marsaglia method. However, for doc purposes using this method, I believe the proposed changes are more clear.

**Comment by bob-carpenter** [comment]
@spinkney:  Is there a reference for the spherical transform plus Jacobian somewhere?  What convinced you we should be using that?   The reason I ask is that @mjhajharia and I are going to try to evaluate a bunch of transforms this summer for numerical accuracy and efficiency. 

A longer-term goal is adding an orthonormal matrix type, for which it has been suggested that we look at taking the matrix exponential of a skew symmetric matrix.  The Jacobian's pretty tricky and all I have are partial references.

**Comment by spinkney** [comment]
You're in luck. I've done the hard work here already. See https://discourse.mc-stan.org/t/a-better-unit-vector/26989

**Comment by spinkney** [comment]
Make a unit vector sized 2 in Stan and sample with defaults. I believe you should see a divergence. Then test this spherical method.

**Comment by bob-carpenter** [comment]
Using this model

```stan
parameters {
  unit_vector[2] alpha;
}
```

I can run in cmdstanr,

```R
> library('cmdstanr')
> mod <- cmdstan_model('units.stan')
> fit <- mod$sample()
```

I don't see any divergences.

```
> fit <- mod$sample()
Running MCMC with 4 sequential chains...

Chain 1 Iteration:    1 / 2000 [  0%]  (Warmup) 
Chain 1 Iteration:  100 / 2000 [  5%]  (Warmup) 
Chain 1 Iteration:  200 / 2000 [ 10%]  (Warmup) 
Chain 1 Iteration:  300 / 2000 [ 15%]  (Warmup) 
Chain 1 Iteration:  400 / 2000 [ 20%]  (Warmup) 
Chain 1 Iteration:  500 / 2000 [ 25%]  (Warmup) 
Chain 1 Iteration:  600 / 2000 [ 30%]  (Warmup) 
Chain 1 Iteration:  700 / 2000 [ 35%]  (Warmup) 
Chain 1 Iteration:  800 / 2000 [ 40%]  (Warmup) 
Chain 1 Iteration:  900 / 2000 [ 45%]  (Warmup) 
Chain 1 Iteration: 1000 / 2000 [ 50%]  (Warmup) 
Chain 1 Iteration: 1001 / 2000 [ 50%]  (Sampling) 
Chain 1 Iteration: 1100 / 2000 [ 55%]  (Sampling) 
Chain 1 Iteration: 1200 / 2000 [ 60%]  (Sampling) 
Chain 1 Iteration: 1300 / 2000 [ 65%]  (Sampling) 
Chain 1 Iteration: 1400 / 2000 [ 70%]  (Sampling) 
Chain 1 Iteration: 1500 / 2000 [ 75%]  (Sampling) 
Chain 1 Iteration: 1600 / 2000 [ 80%]  (Sampling) 
Chain 1 Iteration: 1700 / 2000 [ 85%]  (Sampling) 
Chain 1 Iteration: 1800 / 2000 [ 90%]  (Sampling) 
Chain 1 Iteration: 1900 / 2000 [ 95%]  (Sampling) 
Chain 1 Iteration: 2000 / 2000 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.
Chain 2 Iteration:    1 / 2000 [  0%]  (Warmup) 
Chain 2 Iteration:  100 / 2000 [  5%]  (Warmup) 
Chain 2 Iteration:  200 / 2000 [ 10%]  (Warmup) 
Chain 2 Iteration:  300 / 2000 [ 15%]  (Warmup) 
Chain 2 Iteration:  400 / 2000 [ 20%]  (Warmup) 
Chain 2 Iteration:  500 / 2000 [ 25%]  (Warmup) 
Chain 2 Iteration:  600 / 2000 [ 30%]  (Warmup) 
Chain 2 Iteration:  700 / 2000 [ 35%]  (Warmup) 
Chain 2 Iteration:  800 / 2000 [ 40%]  (Warmup) 
Chain 2 Iteration:  900 / 2000 [ 45%]  (Warmup) 
Chain 2 Iteration: 1000 / 2000 [ 50%]  (Warmup) 
Chain 2 Iteration: 1001 / 2000 [ 50%]  (Sampling) 
Chain 2 Iteration: 1100 / 2000 [ 55%]  (Sampling) 
Chain 2 Iteration: 1200 / 2000 [ 60%]  (Sampling) 
Chain 2 Iteration: 1300 / 2000 [ 65%]  (Sampling) 
Chain 2 Iteration: 1400 / 2000 [ 70%]  (Sampling) 
Chain 2 Iteration: 1500 / 2000 [ 75%]  (Sampling) 
Chain 2 Iteration: 1600 / 2000 [ 80%]  (Sampling) 
Chain 2 Iteration: 1700 / 2000 [ 85%]  (Sampling) 
Chain 2 Iteration: 1800 / 2000 [ 90%]  (Sampling) 
Chain 2 Iteration: 1900 / 2000 [ 95%]  (Sampling) 
Chain 2 Iteration: 2000 / 2000 [100%]  (Sampling) 
Chain 2 finished in 0.0 seconds.
Chain 3 Iteration:    1 / 2000 [  0%]  (Warmup) 
Chain 3 Iteration:  100 / 2000 [  5%]  (Warmup) 
Chain 3 Iteration:  200 / 2000 [ 10%]  (Warmup) 
Chain 3 Iteration:  300 / 2000 [ 15%]  (Warmup) 
Chain 3 Iteration:  400 / 2000 [ 20%]  (Warmup) 
Chain 3 Iteration:  500 / 2000 [ 25%]  (Warmup) 
Chain 3 Iteration:  600 / 2000 [ 30%]  (Warmup) 
Chain 3 Iteration:  700 / 2000 [ 35%]  (Warmup) 
Chain 3 Iteration:  800 / 2000 [ 40%]  (Warmup) 
Chain 3 Iteration:  900 / 2000 [ 45%]  (Warmup) 
Chain 3 Iteration: 1000 / 2000 [ 50%]  (Warmup) 
Chain 3 Iteration: 1001 / 2000 [ 50%]  (Sampling) 
Chain 3 Iteration: 1100 / 2000 [ 55%]  (Sampling) 
Chain 3 Iteration: 1200 / 2000 [ 60%]  (Sampling) 
Chain 3 Iteration: 1300 / 2000 [ 65%]  (Sampling) 
Chain 3 Iteration: 1400 / 2000 [ 70%]  (Sampling) 
Chain 3 Iteration: 1500 / 2000 [ 75%]  (Sampling) 
Chain 3 Iteration: 1600 / 2000 [ 80%]  (Sampling) 
Chain 3 Iteration: 1700 / 2000 [ 85%]  (Sampling) 
Chain 3 Iteration: 1800 / 2000 [ 90%]  (Sampling) 
Chain 3 Iteration: 1900 / 2000 [ 95%]  (Sampling) 
Chain 3 Iteration: 2000 / 2000 [100%]  (Sampling) 
Chain 3 finished in 0.0 seconds.
Chain 4 Iteration:    1 / 2000 [  0%]  (Warmup) 
Chain 4 Iteration:  100 / 2000 [  5%]  (Warmup) 
Chain 4 Iteration:  200 / 2000 [ 10%]  (Warmup) 
Chain 4 Iteration:  300 / 2000 [ 15%]  (Warmup) 
Chain 4 Iteration:  400 / 2000 [ 20%]  (Warmup) 
Chain 4 Iteration:  500 / 2000 [ 25%]  (Warmup) 
Chain 4 Iteration:  600 / 2000 [ 30%]  (Warmup) 
Chain 4 Iteration:  700 / 2000 [ 35%]  (Warmup) 
Chain 4 Iteration:  800 / 2000 [ 40%]  (Warmup) 
Chain 4 Iteration:  900 / 2000 [ 45%]  (Warmup) 
Chain 4 Iteration: 1000 / 2000 [ 50%]  (Warmup) 
Chain 4 Iteration: 1001 / 2000 [ 50%]  (Sampling) 
Chain 4 Iteration: 1100 / 2000 [ 55%]  (Sampling) 
Chain 4 Iteration: 1200 / 2000 [ 60%]  (Sampling) 
Chain 4 Iteration: 1300 / 2000 [ 65%]  (Sampling) 
Chain 4 Iteration: 1400 / 2000 [ 70%]  (Sampling) 
Chain 4 Iteration: 1500 / 2000 [ 75%]  (Sampling) 
Chain 4 Iteration: 1600 / 2000 [ 80%]  (Sampling) 
Chain 4 Iteration: 1700 / 2000 [ 85%]  (Sampling) 
Chain 4 Iteration: 1800 / 2000 [ 90%]  (Sampling) 
Chain 4 Iteration: 1900 / 2000 [ 95%]  (Sampling) 
Chain 4 Iteration: 2000 / 2000 [100%]  (Sampling) 
Chain 4 finished in 0.0 seconds.

All 4 chains finished successfully.
Mean chain execution time: 0.0 seconds.
Total execution time: 0.7 seconds.
```

The effective sample sizes are estimated to be roughly the number of draws (4000).

```R
> fit
 variable  mean median   sd  mad    q5   q95 rhat ess_bulk ess_tail
 lp__     -1.03  -0.73 1.02 0.73 -3.12 -0.05 1.00     1577     2141
 alpha[1]  0.00   0.00 0.70 1.03 -0.99  0.99 1.00     4236     3550
 alpha[2]  0.01   0.03 0.71 1.06 -0.98  0.99 1.00     3749     3278prints this
```

I also don't see any divergences running in 10, 100, or 1000 dimensions (that's as far as I went).  In fact, the ESS gets better per draw as the number of dimensions goes up, averaging around ESS = 6000 for 4000 draws in 100 and ESS = 8000 for 4000 draws in 1000 dimensions.

**Comment by bob-carpenter** [comment]
Anyway, I'm going to go ahead and merge this updated doc.  We should be having the discussion of the actual transform somewhere other than in docs.  I'll move my above discussion to Discourse.

**Comment by bob-carpenter** [comment]
Oh, I didn't mean to close that before merging.  But it won't let me re-open because GitHub tells me the repository that created the PR has been deleted.  Can you resubmit @spinkney?  Sorry for the hassle here.

**Comment by spinkney** [comment]
Yes, this will most likely have to wait until you're back. I'm on vacation and probably won't get to it this week.

**Comment by WardBrian** [comment]
@bob-carpenter you could merge it the only fashioned way by downloading the patch: https://github.com/stan-dev/docs/pull/331.patch

**Comment by bob-carpenter** [comment]
Thanks, @WardBrian.  How do I merge the patch?  It only shows up in text when I click on it.

**Comment by WardBrian** [comment]
You’d have to download it to a file, apply it to master with [git apply](https://git-scm.com/docs/git-apply), and then push. Alternatively you could apply it to a new branch and open a fresh PR from there 

A few projects use this instead of ever pushing the merge button on GitHub, I think mostly because it lets they customize the merge message better?

**Comment by bob-carpenter** [comment]
I'm terrified of working with the master branch on Git even with operations I think I understand, so that's way too scary for me to try.  But with the diff I can just make the changes manually in a new PR if @spinkney doesn't still have the branch.

**Comment by spinkney** [comment]
I believe I deleted it. Go forth and do what you gotta do to get this in

**Pull request closed without merging**
