### PR TITLE
Issue/686 - Rmd rendering in bookdown and quarto 

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Builds locally 
- [x] New functions marked with `` `r since("VERSION")` ``
- [x] Declare copyright holder and open-source license: see below

#### Summary

changed use of `\[` and `/]` to `\begin{equation*}` and `\end{equation*}` so that Rmd files can render using either bookdown or quarto.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
This is a work in progress - but as it will touch a lot of files, I wanted y'all to get a sense of what I propose to do here.

At this point, I have changed the Rmd files for the functions reference and verified that the HTML can render using either quarto or bookdown (i.e., current build scripts).    I also found a few omissions and fixed a couple of rendering issues.

**Comment by mitzimorris** [comment]
fixed problems with build - now builds both pdf and html on my machine.
I've skimmed both versions, checking that equations look OK and that fit on the fixed pdf page width.
@WardBrian - let me know if it builds for you.

next up, figuring out how to build functions ref pdf using quarto - unless we want to recombine all ref manuals into a single pdf.

**Comment by WardBrian** [comment]
Builds now, thanks!

**Comment by mitzimorris** [comment]
This is ready for review - all Rmd files now render correctly as quarto html pages and as bookdown html and pdfs.

I also used quarto to build a pdf book version of the functions reference, which turned up a few stray miscodings of the index entries.   The other documents don't include an index.  To build a pdf with quarto, I needed to create a `_quarto.yml`.   I will check that work into a new sub-branch - I think that it would be best to merge this set of cleanups first.

@WardBrian - do you have cycles for this?

**Comment by WardBrian** [comment]
Maybe not tomorrow but should be able to get to it before Thanksgiving certainly

**Review by WardBrian — APPROVED** [review]
Looks good - I needed to re-install bookdown to get the build working, so maybe the README should mention a newer version than 0.23. Since the eventual goal is to move away from bookdown entirely I don't think we need to be particularly conservative with requiring older versions or anything

**Pull request merged**
