### PR TITLE
Docs generated by Jenkins for v2-23

### PR DESCRIPTION
**Pull request by stan-buildbot**
Docs generated through the [Jenkins Job](https://jenkins.mc-stan.org/job/BuildDocs/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal this was closed without merging?

**Comment by serban-nicusor-toptal** [comment]
Yes, I thought there are new changed so I am now rebuilding them. here https://jenkins.mc-stan.org/job/BuildDocs/24/console
But it will take a while

**Comment by mitzimorris** [comment]
great, many thanks!
sorry for the public nag on the forums.

**Comment by serban-nicusor-toptal** [comment]
No worries at all! I am also waiting for it to complete while watching Jenkins/AWS.
There is a very high load in spot and normal instances so some of ours got outbid and terminated :( I hope it's stable now.

**Pull request closed without merging**
