### PR TITLE
recreation of 'footnotes' branch that somehow got messed up. 

### PR DESCRIPTION
**Pull request by breckbaldwin**
Previous PR is https://github.com/stan-dev/docs/pull/164. PR was showing 3k changes, something went wrong. This hopefully encapsulates the changes minimally.  

Done at request of @bbbales2. 

#### Submission Checklist

- [ x] Builds locally 
- [ x] Declare copyright holder and open-source license: see below

#### Summary
Adding example_code directory and modifying regression.Rmd, the initial sections of Stan User's Guide. 
Andrew Gelman idea. 
This covers up to but not including Multnomial Logistic Regression section. More added later. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University.

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by breckbaldwin** [comment]
Files changed is now down to 30 which makes sense. 

No idea how we got 2k changes before, if you can explain pls do. Maybe my rebase fouled things up.

**Comment by mitzimorris** [comment]
this is in not ready to merge into master.

**Comment by mitzimorris** [comment]
apologies for closing this - forgot that this was just to share a WIP.

**Comment by bbbales2** [comment]
I think this can close.

**Pull request closed without merging**
