### PR TITLE
Sentence case titles

### LINKED ISSUE #154: Fix capitalization in titles
#### Summary:
This is the rule @bob-carpenter suggested in https://github.com/stan-dev/docs/pull/148#discussion_r383437917:

*  `# XXX` uses title punctuation for XXX (all caps other than "function" words [prepositions, determiners, auxliary verbs, other particles, etc.])

*  `## XXX` should use sentence punctuation for XXX (initial caps, not all caps)

#### Current Version:
v2.18.0

### LINKED ISSUE #184: Stan Functions Reference: Typo for Dirichlet distribution?
#### Description:
There might be a typo in the Stan Functions Reference (section 22.1. "Dirichlet Distribution"; p. 127 of the PDF version or [this page](https://mc-stan.org/docs/2_22/functions-reference/dirichlet-distribution.html) of the HTML version):
It says

> Taking K = 10, here are the first five draws for α = 0.001.

but I think it's meant to be

> Taking K = 10, here are the first five draws for α = 1.

#### Current Version:
v2.22.0

### LINKED ISSUE #291: squared_distance docs have extra brackets
#### Summary:

At the end of this page: https://mc-stan.org/docs/2_25/functions-reference/array-reductions.html

The squared_distance functions have extra brackets.

`real squared_distance(vector x, row_vector [] y)`

should be:

`real squared_distance(vector x, row_vector y)`

### PR DESCRIPTION
**Pull request by Alanocallaghan**
#### Submission Checklist

- [x] Builds locally
- [x] Declare copyright holder and open-source license: see below

#### Summary

Consistent `Sentence case` in subtitles (`## Subtitle` or lower) rather than `Title Case`. Resolve #154

Remove errant brackets in `squared_distance` help in `array_operations`; resolve #291

Fix typo in Dirichlet documentation; resolve #184 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Alan O'Callaghan

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks @Alanocallaghan, much appreciated!

**Comment by Alanocallaghan** [comment]
No worries, there are worse things in this world than some Philip Glass and a repetitive task

**Comment by rok-cesnovar** [comment]
@Alanocallaghan thanks for doing this! Would you mind merging in the master branch now that we merged #300 that overlaps with this one a bit?

**Comment by Alanocallaghan** [comment]
Done

**Review by rok-cesnovar — APPROVED** [review]
Thank you so much for doing this! Looks good to merge.

**Comment by Alanocallaghan** [comment]
My pleasure - glad to give back given how great Stan has been for my work and how great the community has been to me :heart:

**Pull request merged**
